[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Caching = "68ad905a-5087-500a-aae7-0fd6acda2eb1"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
